version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "4269:80"
    volumes:
      - ./dist:/usr/share/nginx/html
  cloudflare-tunnel:
    container_name: cloudflare-tunnel
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDEFLARE_TUNNEL_TOKEN}
    volumes:
      - ${HOME_BASE_DIR}/cloudflare-tunnel/config:/etc/cloudflared
  cloudflare-tunnel-2:
    container_name: cloudflare-tunnel-2
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${CLOUDEFLARE_TUNNEL_TOKEN_2}
    volumes:
      - ${HOME_BASE_DIR}/cloudflare-tunnel-2/config:/etc/cloudflared